Lesson... impl methods take the reference to self as first arg
Was getting these errors, that were not terribly helpful but forced me
to walk through the code to find the resolution:
Ans: &self

(not snippet from next commit compilation with the improper self
assignment Just split up to be explicit about this earned knowledge)

me@machine:[rust_web_hello_world]:[main*↑19]:[128079]> cargo test
   Compiling rust_web_hello_world v0.1.0 (/Users/me/projects/rust_web_hello_world)
error[E0507]: cannot move out of `*config` which is behind a shared reference
  --> tests/health_check.rs:47:49
   |
47 |     let mut connection = PgConnection::connect(&config.connection_string_wo_database()).await.expect("Failed to connect to Postgres");
   |                                                 ^^^^^^^-------------------------------
   |                                                 |      |
   |                                                 |      `*config` moved due to this method call
   |                                                 move occurs because `*config` has type `DatabaseSettings`, which does not implement the `Copy` trait
   |
note: this function takes ownership of the receiver `self`, which moves `*config`
  --> /Users/me/projects/rust_web_hello_world/src/configuration.rs:32:42
   |
32 |     pub fn connection_string_wo_database(self) -> String {
   |                                          ^^^^

error[E0507]: cannot move out of `*config` which is behind a shared reference
  --> tests/health_check.rs:53:44
   |
53 |     let connection_pool = PgPool::connect(&config.connection_string()).await.expect("Failed to connect to Postgres");
   |                                            ^^^^^^^-------------------
   |                                            |      |
   |                                            |      `*config` moved due to this method call
   |                                            move occurs because `*config` has type `DatabaseSettings`, which does not implement the `Copy` trait
   |
note: this function takes ownership of the receiver `self`, which moves `*config`
  --> /Users/me/projects/rust_web_hello_world/src/configuration.rs:23:30
   |
23 |     pub fn connection_string(self) -> String {
   |                              ^^^^